function cfg = brsr_config(varargin)
% BRSR_CONFIG  Default settings of the BRSR dataset generator (name/value pairs override them).
%   cfg = brsr_config('mode', 'brsr', 'seed', 0, 'n_train', 400, 'n_test', 150)
%
%   mode            'brsr' (random blend of AWGN, echo and interference) or 'awgn' (AWGN only)
%   seed            random seed (rng)
%   n_train/n_test  signals per class per SNR level in the train/test run
%   param_sampling  'grid' (as in BRSR v1.0: permuted linspace grids) or 'uniform'
%   legacy_lfm      true reproduces the BRSR v1.0 LFM amplitude behaviour (see waveforms/type_LFM.m)
cfg = struct( ...
    'mode', 'brsr', ...
    'seed', 0, ...
    'fs', 100e6, ...
    'amplitude', 1, ...
    'n_samples', 1024, ...
    'long_factor', 2, ...
    'snr_min', -14, ...
    'snr_max', 10, ...
    'snr_levels', -14:2:10, ...
    'n_train', 400, ...
    'n_test', 150, ...
    'val_fraction', 0.2, ...
    'param_sampling', 'grid', ...
    'legacy_lfm', true, ...
    'echo_delay', [128 512], ...
    'classes', {{'LFM','Costas','BPSK','Frank','P1','P2','P3','P4','T1','T2','T3','T4'}}, ...
    'interference_bank', fullfile(fileparts(mfilename('fullpath')), 'interference_bank.mat'));
for k = 1:2:numel(varargin)
    if ~isfield(cfg, varargin{k}), error('brsr_config: unknown option %s', varargin{k}); end
    cfg.(varargin{k}) = varargin{k+1};
end
end
